---
- name: copy backend dist
  copy:
    src: ../../backend.tgz
    dest: /home/ubuntu/udapeople

- name: copy package.json
  copy:
    src: ../../backend/package.json
    dest: /home/ubuntu/udapeople

- name: install app
  shell: npm install --production
  args:
    chdir: /home/ubuntu/udapeople

- name: unzip dist files
  shell: |
    tar -xzvf backend.tgz
  args:
    chdir: /home/ubuntu/udapeople

- name: start the app
  shell: |
    echo $TYPEORM_CONNECTION > env_vars.txt
    echo $TYPEORM_HOST >> env_vars.txt
    echo $TYPEORM_PORT >> env_vars.txt
    export ENVIRONMENT=production
    export NODE_ENV=production
    pm2 start main.js --name udapeople
  args:
    chdir: /home/ubuntu/udapeople