version: 2.1

node-image: &node-image
  docker:
    - image: circleci/node:13.8.0

aws-cli-image: &aws-cli-image
  docker:
    - image: amazon/aws-cli

ansible-image: &ansible-image
  docker:
    - image: python:3.7-alpine3.11

lightweight-image: &lightweight-image
  docker:
    - image: ansible

orbs:
  aws-s3: circleci/aws-s3@2.0.0

commands:
  destroy-environments:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID}
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID}/ --recursive
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID}

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            export SUCCESS=$(curl -sH "token: ${CIRCLE_WORKFLOW_ID}" --request GET "https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}" | grep -c "has been executed successfully")
            if [ "$SUCCESS" == 1 ];
            then
              cd ./backend
              npm install
              npm run migrations:revert
            fi
            
jobs:
  build-frontend:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-build-{{ checksum "frontend/package.json" }}
      - run:
          name: Build front-end
          working_directory: frontend
          command: npm install && npm run build
      - save_cache:
          paths: [/home/circleci/project/frontend/node_modules]
          key: frontend-build-{{ checksum "frontend/package.json" }}

  build-backend:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-build-{{ checksum "backend/package.json" }}
      - run:
          name: Back-end build
          working_directory: backend
          command: npm install && npm run build
      - save_cache:
          paths:
            - /home/circleci/project/backend/node_modules
            - /home/circleci/project/backend/dist
          key: backend-build-{{ checksum "backend/package.json" }}

  test-frontend:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-build-{{ checksum "frontend/package.json" }}
      - run:
          name: Test frontend
          working_directory: frontend
          command: npm test
                
  test-backend:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-build-{{ checksum "backend/package.json" }}
      - run:
          name: Test backend
          working_directory: backend
          command: npm test

  scan-frontend:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-build-{{ checksum "frontend/package.json" }}
      - run:
          name: Scan frontend dependencies
          working_directory: frontend
          command: npm audit --audit-level=critical

  scan-backend:
    <<: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-build-{{ checksum "backend/package.json" }}
      - run:
          name: Scan backend dependencies
          working_directory: backend
          command: npm audit --audit-level=critical

  deploy-infrastructure:
    <<: *aws-cli-image
    steps:
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          command: |
              aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
               --tags project=udapeople \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
      - run:
          name: Ensure front-end infrastructure exist
          command: |
              aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
              --output text | tee .circleci/ansible/inventory.txt .circleci/ansible/ec2-ip.txt
      - run:
          name: Install dependencies for persist_to_workspace
          command: yum -y install tar gzip
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/ansible/inventory.txt
            - .circleci/ansible/ec2-ip.txt
      - destroy-environments

  configure-infrastructure:
    <<: *ansible-image
    steps:
      - checkout
      - run:
          name: Install dependencies for attach_workspace
          command: apk add --update tar gzip
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints: ["23:c9:71:07:b1:8e:81:ee:ae:5e:48:35:a6:9f:65:f9"]
      - run:
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook .circleci/ansible/configure-server.yml -i .circleci/ansible/inventory.txt
      - run:
          name: Install awscli
          when: on_fail
          command: |
            apk add --update curl && \
            apk add --update unzip && \
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            unzip awscliv2.zip && \
            ./aws/install
      - destroy-environments

  run-migrations:
    <<: *node-image
    steps:
      - checkout
      - run:
          command: sudo apt-get install -y tar gzip curl
      - restore_cache:
          keys:
            - backend-build-{{ checksum "backend/package.json" }}
      - run:
          name: Run migrations
          working_directory: backend
          command: |
            npm run migrations > migrations-result.txt
      - run:
          name: Send migration results to memstash
          command: |
            curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" --request PUT --data `cat ./backend/migrations-result.txt` https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
      - run:
          when: on_fail
          command: sudo apt-get update && sudo apt-get install -y awscli curl grep
      - revert-migrations
      - destroy-environments

  deploy-frontend:
    <<: *node-image
    steps:
      - checkout
      - run:
          command: sudo apt-get install -y tar gzip
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - frontend-build-{{ checksum "frontend/package.json" }}
      - run:
          command: sudo apt-get update && sudo apt-get install -y grep
      - run:
          name: Build frontend with baked-in API_URL
          command: |
            export API_URL="http://`cat .circleci/ansible/ec2-ip.txt`:3030" && \
            cd ./frontend && \
            npm run build
      - aws-s3/copy:
          arguments: "--recursive"
          from: ./frontend/dist
          to: "s3://udapeople-${CIRCLE_WORKFLOW_ID}"
      - run:
          when: on_fail
          command: sudo apt-get update && sudo apt-get install -y awscli curl
      - revert-migrations
      - destroy-environments
                    
  deploy-backend:
    <<: *ansible-image
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["23:c9:71:07:b1:8e:81:ee:ae:5e:48:35:a6:9f:65:f9"]
      - run:
          name: Install dependencies for attach_workspace
          command: apk add --update tar gzip
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - backend-build-{{ checksum "backend/package.json" }}
      - run:
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: zip dist files
          command: cd /home/circleci/project/backend/dist && tar -czf /root/project/backend.tgz *
      - run:
          name: Deploy backend
          command: |
            ansible-playbook .circleci/ansible/deploy-backend.yml -i .circleci/ansible/inventory.txt
      - run:
          name: Install awscli
          when: on_fail
          command: |
            apk add --update curl && \
            apk add --update unzip && \
            apk add --update grep && \
            apk add --update nodejs npm && \
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            unzip awscliv2.zip && \
            ./aws/install
      - revert-migrations
      - destroy-environments

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add curl
            apk add tar
            apk add grep
            apk add gzip
            apk add ansible
            apk add --update nodejs npm
            pip3 install awscli
      - attach_workspace:
          at: .
      - run:
          name: Backend smoke test.
          command: |
            #export API_URL="http://`cat .circleci/ansible/ec2-ip.txt`:3031"
            export API_URL="http://localhost:3031"
            curl -v "${API_URL}"
            if curl -s "${API_URL}" | grep ok
            then
              return 0
            else
              return 1
            fi
      - run:
          name: Frontend smoke test.
          command: |
            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website.us-west-2.amazonaws.com/"
            curl -v "${FRONTEND_URL}"
            if curl -s ${FRONTEND_URL} | grep "Welcome"
            then
              return 0
            else
              return 1
            fi
      - revert-migrations
      - destroy-environments

  cloudfront-update:
    <<: *aws-cli-image
    steps:
      # Checkout code from git
      - run:
          name: Install dependencies
          command: |
            # your code here
      - run:
          name: Update cloudfront distribution
          command: |
            # your code here
      # Here's where you will add some code to rollback on failure  

  cleanup:
    <<: *lightweight-image
    steps:
      # Checkout code from git
      - run:
          name: Get old stack workflow id
          command: |
            # your code here
            export OldWorkflowID="the id here"
            export STACKS=[] #put the list of stacks here
      - run:
          name: Remove old stacks and files
          command: |
            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then
              # your code here
            fi

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [final-project]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - run-migrations:
          requires: [configure-infrastructure]
      - deploy-frontend:
          requires: [run-migrations]
      - deploy-backend:
          requires: [run-migrations]
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
      - cloudfront-update:
          requires: [smoke-test]
      - cleanup:
          requires: [cloudfront-update]